### ISSUE TITLE
Конфигурация

### ISSUE THREAD

**Issue by GoncharovArtyom** [MurzinR/First_Project#2]
https://github.com/MurzinR/First_Project/blob/29ebf56e8e4ff6e6f03545ccf9241fecf93a8494/config.py#L5

Нужно ли создавать дополнительный класс Config внутри файла config.py? Кажется, что он не имеет никакого смысла, а все его внутренние статические поля можно просто перенести на уровень модуля.

**Comment by GoncharovArtyom** [comment]
Кстати, не нужно явно указывать наследование от object - это происходит автоматически.

**Comment by MurzinR** [comment]
Перенес поля в словарь config.
