### ISSUE TITLE
Фреймворк для тестов

### ISSUE THREAD

**Issue by GoncharovArtyom** [MurzinR/First_Project#3]
https://github.com/MurzinR/First_Project/blob/29ebf56e8e4ff6e6f03545ccf9241fecf93a8494/tests.py#L6

Если уж мы пишем на питоне, то лучше пользоваться pytest - он очень удобный, на самом деле, хотя поначалу кажется запутанным. Почитай документацию и попробуй переписать тесты.

**Comment by MurzinR** [comment]
Написал тесты с помощью pytest.

**Comment by GoncharovArtyom** [comment]
Окей. Кстати, лучше не сравнивать полученный ответ от сервера с ожидаемым в виде строк, потому что для формата JSON не задан порядок ключей. То есть {"a": 1, "b": 2} совпадает с {"b": 2, "a": 1}, но если сравнивать их как строки, то они не будут равны. Лучше привести все к словарям, если ты хочешь именно json сравнить.
