### ISSUE TITLE
Тип статуса

### ISSUE THREAD

**Issue by GoncharovArtyom** [MurzinR/First_Project#6]
https://github.com/MurzinR/First_Project/blob/29ebf56e8e4ff6e6f03545ccf9241fecf93a8494/app/models.py#L8

Если некоторое поле может принимать только определенные значения, то его тип должен быть перечислением.

**Comment by MurzinR** [comment]
Поменял тип статуса.

**Comment by GoncharovArtyom** [comment]
Лучше создать перечисление отдельным классом, чтобы можно было им пользоваться из питоновского кода. Вот так:

![image](https://user-images.githubusercontent.com/15707604/63014191-a4c11580-be96-11e9-9a41-db95e7e22c6e.png)
